### ISSUE TITLE
Readme / Requirements

### ISSUE THREAD

**Issue by Kip7777** [hnrq/veloren-server-arm#2]
I ran through your readme / install guide and it failed on fresh install of Ubuntu 22.04 on Oracle Cloud Always Free due to lack of unzip in the default image provided by Oracle. You might like to consider listing unzip as a prerequisite before running your script. Ubuntu users can use `'sudo apt install unzip'` before running your script. 

A cleaner solution might be for your script to check unzip is present on the system first and halting with an error message if it is not, rather than continuing and telling a novice user that all is well. 

Running the uninstall script, then installing unzip, then re-running your script did not solve the problem. I terminated the server and made a new one, updated the system, installed unzip, ran your script, setup ufw and was then able to login from airshipper and play. :) A quad core Ampere shape provides much better performance than the single core Micro shape available on Oracle Always Free.

Given that basically anyone can grab a free Oracle Ampere VM, this script is brilliant for enabling an easy to deploy aarch64 Veloren server, so thank you for sharing it with the world.

**Comment by hnrq** [comment]
Thanks for the suggestion, dude! I'll submit a PR for that
