### ISSUE TITLE
Auto update broken?

### ISSUE THREAD

**Issue by Kip7777** [hnrq/veloren-server-arm#3]
I don't know if this is just a quirk on my system (Ubuntu Server 22.04.1 LTS (GNU/Linux 5.15.0-1018-oracle aarch64)), but, I've had my server up almost a week now and so I've had the opportunity to see if it auto updates. It didn't, however, running sudo /usr/bin/update-veloren-server got it updated. As I dug into my services, I found this:

`systemctl status veloren-server.timer`
● veloren-server.timer - Run update-veloren-server periodically
     Loaded: loaded (/etc/systemd/system/veloren-server.timer; enabled; vendor preset: enabled)
     Active: active (running) since Tue 2022-10-04 19:04:07 BST; 2 days ago
    Trigger: n/a
   Triggers: ● veloren-server.service

Oct 04 19:04:07 hostname systemd[1]: Started Run update-veloren-server periodically.
Oct 06 21:42:39 hostname systemd[1]: **/etc/systemd/system/veloren-server.timer:5: Unit type not valid, ignoring: "oneshot-update-veloren-server.service"**

The last line above was highlighted on my system so I can only assume something is up but I couldn't figure that bit out. 

So, having never played with systemd before, I tried the following:

I removed the line: `Unit="oneshot-update-veloren-server.service"` from veloren-server.timer as it was ignoring this line anyway for whatever reason, probably defaulting on trying to run the actual server every 15 minutes since the .timer name matches the server .service name.  

 `systemctl stop veloren-server.timer`
 `systemctl disable veloren-server.timer`

 `mv oneshot-update-veloren-server.service update-veloren-server.service`
 `mv veloren-server.timer update-veloren-server.timer`

 `systemctl enable update-veloren-server.timer`
 `systemctl start update-veloren-server.timer`

This appears to have fixed things but as a total novice I always doubt my own tinkering around:

`systemctl status update-veloren-server`
○ update-veloren-server.service - One shot update Veloren server service
     Loaded: loaded (/etc/systemd/system/update-veloren-server.service; disabled; vendor preset: enabled)
     Active: inactive (dead) since Thu 2022-10-06 23:15:06 BST; 3min 33s ago
TriggeredBy: ● update-veloren-server.timer
    Process: 16925 ExecStart=/usr/bin/update-veloren-server (code=exited, status=0/SUCCESS)
   Main PID: 16925 (code=exited, status=0/SUCCESS)
        CPU: 93ms

Oct 06 23:15:06 hostname systemd[1]: Starting One shot update Veloren server service...
Oct 06 23:15:06 hostname update-veloren-server[16925]: Your server is up-to-date!
Oct 06 23:15:06 hostname systemd[1]: update-veloren-server.service: Deactivated successfully.
Oct 06 23:15:06 hostname systemd[1]: Finished One shot update Veloren server service.

15 minutes later, it ran again returning a success. Hopefully next week my server will auto update.

**Comment by hnrq** [comment]
I had problems with autoupdate last week and the latest commit fixed it. Could you try updating?

**Comment by hnrq** [comment]
Also, I should probably add to the readme that the update-veloren-server script can be run with a -f flag for forcing an update

**Comment by Kip7777** [comment]
> I had problems with autoupdate last week and the latest commit fixed it. Could you try updating?

If you're refering to these commits: [https://github.com/hnrq/veloren-server/commit/3cc119a1c4ec1d0009bdc4137cb91a474606d563](url) and [https://github.com/hnrq/veloren-server/commit/1df1b4933ac6c332cbb9dcc5c2ff606920a88804](url) then my server was set up and installed after those commits were added. I do remember seeing new commits made just hours before I ran your script. 

Running `stat` returns Birth: 2022-09-30 20:23:48.xxxxxxxxx +0100 on all my Veloren files, other than the odd one or two that I've messed with or were updated by my manual update.

**Comment by hnrq** [comment]
Could you send the output of `cat /usr/bin/update-veloren-server`?

**Comment by Kip7777** [comment]
```
#!/bin/bash
FORCE_UPDATE="false"
ARCHITECTURE="$(uname -m)"
FILENAME="veloren-$ARCHITECTURE"
REMOTE_VER="$(curl -s "https://download.veloren.net/version/linux/$ARCHITECTURE/weekly")"
VELOREN_INSTALL_DIR=/usr/veloren-server
SERVICE_NAME=veloren-server

mkdir -p $VELOREN_INSTALL_DIR
touch $VELOREN_INSTALL_DIR/version

while test "$#" -gt 0; do
case "$1" in
-f|--force) 
FORCE_UPDATE="true"
shift
;;
*)
break
;;
esac
done

if [[ $REMOTE_VER = "$(cat $VELOREN_INSTALL_DIR/version 2>/dev/null)" && $FORCE_UPDATE == "false" ]]; then
printf "\n\e[32m\e[1mYour server is up-to-date!\e[0m\n"
else
printf "\nDownloading Veloren server version %s...\n" "$REMOTE_VER"
curl -#L -o "$VELOREN_INSTALL_DIR/$FILENAME" --connect-timeout 30 --max-time 30 --retry 300 --retry-delay 5 "https://download.veloren.net/latest/linux/$ARCHITECTURE/weekly"
unzip -qo "$VELOREN_INSTALL_DIR/$FILENAME" -d "$VELOREN_INSTALL_DIR" && rm $VELOREN_INSTALL_DIR/$FILENAME

# Restart System
if [[ $(systemctl list-units --all -t service --full --no-legend "$SERVICE_NAME.service" | sed 's/^\s*//g' | cut -f1 -d' ') == $SERVICE_NAME.service ]]; then
systemctl restart "$SERVICE_NAME.service"
fi

printf "\e[32m\e[1mSuccessfully downloaded latest version (%s)\e[0m\n" "$REMOTE_VER"
printf "%s" "$REMOTE_VER" > "$VELOREN_INSTALL_DIR/version"
fi

```

**Comment by hnrq** [comment]
> Unit="oneshot-update-veloren-server.service"

Hmmm, that's interesting... I'll take a look at that
